<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.76"/>
    <xacro:property name="chassis_width" value="0.66"/>   
    <xacro:property name="chassis_height" value="0.28"/>
    <xacro:property name="chassis_mass" value="7.2"/>
    <xacro:property name="wheel_radius" value="0.095"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_mass" value="1.3"/>
    <xacro:property name="wheel_offset_x" value="0.38"/>
    <xacro:property name="wheel_offset_y" value="0.3625"/>
    <xacro:property name="wheel_offset_z" value="0.07"/>
    <xacro:property name="caster_wheel_radius" value="0.095"/>
    <xacro:property name="caster_wheel_mass" value="0.4"/>
    <xacro:property name="caster_wheel_offset_x" value="0.33"/>
    <xacro:property name="caster_wheel_offset_z" value="0.05"/>
    <xacro:property name="column_length" value="0.03"/>
    <xacro:property name="column_width" value="0.03"/>   
    <xacro:property name="column_height" value="0.2"/>
    <xacro:property name="column_offset_y" value="0.315"/>
    <xacro:property name="column_offset_z" value="0.375"/>
    <xacro:property name="chassis1_length" value="0.76"/>
    <xacro:property name="chassis1_width" value="0.66"/>   
    <xacro:property name="chassis1_height" value="0.05"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="chassis1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis1"/>
        <origin xyz="${-wheel_offset_x} 0 ${wheel_offset_z+0.3}"/>
    </joint>

    <link name="chassis1">
        <visual>
            <origin xyz="${chassis1_length/2} 0 ${chassis1_height/2}"/>
            <geometry>
                <box size="${chassis1_length} ${chassis1_width} ${chassis1_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis1_length/2} 0 ${chassis1_height/2}"/>
            <geometry>
                <box size="${chassis1_length} ${chassis1_width} ${chassis1_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis1_length}" y="${chassis1_width}" z="${chassis1_height}">
            <origin xyz="${chassis1_length/2} 0 ${chassis1_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis1">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x*2} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel1_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel1"/>
        <origin xyz="0.1 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel1">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel1">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!--gidung1-->

    <joint name="gidung1_joint" type="fixed">
        <parent link="chassis"/>
        <child link="gidung1"/>
        <origin xyz="${wheel_offset_x+0.365} ${column_offset_y} ${column_offset_z}"/>
    </joint>

    <link name="gidung1">
        <visual>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="gidung1">
        <material>Gazebo/White</material>
    </gazebo>
    
    <!--gidung2-->

    <joint name="gidung2_joint" type="fixed">
        <parent link="chassis"/>
        <child link="gidung2"/>
        <origin xyz="${wheel_offset_x-0.365} ${column_offset_y} ${column_offset_z}"/>
    </joint>

    <link name="gidung2">
        <visual>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="gidung2">
        <material>Gazebo/White</material>
    </gazebo>

    <!--gidung3-->

    <joint name="gidung3_joint" type="fixed">
        <parent link="chassis"/>
        <child link="gidung3"/>
        <origin xyz="${wheel_offset_x+0.365} ${-column_offset_y} ${column_offset_z}"/>
    </joint>

    <link name="gidung3">
        <visual>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="gidung3">
        <material>Gazebo/White</material>
    </gazebo>

    <!--gidung4-->

    <joint name="gidung4_joint" type="fixed">
        <parent link="chassis"/>
        <child link="gidung4"/>
        <origin xyz="${wheel_offset_x-0.365} ${-column_offset_y} ${column_offset_z}"/>
    </joint>

    <link name="gidung4">
        <visual>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${column_length} ${column_width} ${column_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="gidung4">
        <material>Gazebo/White</material>
    </gazebo>

    
    

</robot>