<?xml version ="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="urdf_test">

    <!-- MACROS -->
    <xacro:include filename="macros.xacro"/>

    <xacro:property name="chassis_length" value="0.76"/>
    <xacro:property name="chassis_width" value="0.66"/>
    <xacro:property name="chassis_height" value="0.28"/>
    <xacro:property name="chassis_mass" value="7.2"/>
    <xacro:property name="wheel_radius" value="0.095"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_mass" value="1.3"/>
    <xacro:property name="wheel_offset_x" value="0.38"/>
    <xacro:property name="wheel_offset_y" value="0.3625"/>
    <xacro:property name="wheel_offset_z" value="0.07"/>
    <xacro:property name="caster_wheel_radius" value="0.095"/>
    <xacro:property name="caster_wheel_mass" value="0.4"/>
    <xacro:property name="caster_wheel_offset_x" value="0.33"/>
    <xacro:property name="caster_wheel_offset_z" value="0.05"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <!-- BASE_FOOTPRINT LINK -->

    <link name="base_footprint"/>


    <!-- Base LINK -->

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link" />
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- LEFT WHEEL LINK -->

    <joint name="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_link"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="wheel_left_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="wheel_left_link">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_link"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="wheel_right_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="wheel_right_link">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x*2} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel1"/>
        <origin xyz="0.1 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel1">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel1">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!--column1-->

    <joint name="column1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="column1"/>
        <origin xyz="${wheel_offset_x+0.365} 0.315 0.375"/>
    </joint>

    <link name="column1">
        <visual>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="column1">
        <material>Gazebo/White</material>
    </gazebo>

    <!--column2-->
    <joint name="column2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="column2"/>
        <origin xyz="${wheel_offset_x-0.365} 0.315 0.375"/>
    </joint>

    <link name="column2">
        <visual>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="column2">
        <material>Gazebo/White</material>
    </gazebo>

    <!--column3-->

    <joint name="column3_joint" type="fixed">
        <parent link="base_link"/>
        <child link="column3"/>
        <origin xyz="${wheel_offset_x+0.365} -0.315 0.375"/>
    </joint>

    <link name="column3">
        <visual>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="column3">
        <material>Gazebo/White</material>
    </gazebo>

    <!--column4-->

    <joint name="column4_joint" type="fixed">
        <parent link="base_link"/>
        <child link="column4"/>
        <origin xyz="${wheel_offset_x-0.365} -0.315 0.375"/>
    </joint>

    <link name="column4">
        <visual>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.03 0.2"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.8" x="0.03" y="0.03" z="0.2">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="column4">
        <material>Gazebo/White</material>
    </gazebo>


    <joint name="imu_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="imu_link"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="imu_link">
        <collision>
            <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
	            <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
	            <box size="0.01 0.01 0.01"/>
            </geometry>
            <material name="red"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.1"/>
            <inertia
	        ixx="0.00016667" ixy="0.0" ixz="0.0"
	        iyy="0.00016667" iyz="0.0"
	        izz="0.00016667"/>
        </inertial>
    </link>

</robot>